apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks_ruthin
  labels:
    app: my-eks-pipeline_ruthin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eks-pipeline_ruthin
  template:
    metadata:
      labels:
        app: my-eks-pipeline_ruthin
    spec:
      containers:
        - name: my-eks-pipeline_ruthin_container
          image: ubuntu
          ports:
            - containerPort: 80
